In [92]:
import pandas as pd
import numpy as np
from dateutil import parser

In [93]:
#Raw data entry

data = {
    "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
    "fullName": [
        "  Alice Johnson  ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown",
        "Emma Wilson", "TOM  davis", "Jane Miller", "Chris taylor"
    ], 
     "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
    "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
    "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"],
    "JoinDate" : [ 
        "12-04-2021" , "2020.11.01" , "Jan 18, 2022" , "2019/9/25" , "07/05/18" , "2021-10-14" , 
        "2019/12/01" , "2020-03-22" , "May 10th, 2021" , "2022-02-05" 
    ],
    "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
    "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
}

In [94]:
data_frame = pd.DataFrame(data)

data_frame

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,None,Yes
8,109,Jane Miller,HR,None,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [95]:
#Converting the DataFrame object to csv file using "to_csv"
data_frame.to_csv("data/employee_dataset.csv", index=False)

#Loading the csv file
df = pd.read_csv("data/employee_dataset.csv")

df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [96]:
#Exploring dataset using "pd.info()" 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      str
 2   Dept         9 non-null      str
 3   Age          9 non-null      str
 4   Salary($)    9 non-null      str
 5   JoinDate     10 non-null     str
 6   Performance  9 non-null      str
 7   Remote?      9 non-null      str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes

In [97]:
#Knowing the shape (row,column) of the data using ".shape"
df.shape

(10, 8)

In [98]:
#Displaying the first five data using ".head"
df.head()

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes

In [99]:
#Display columns
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='str')

In [100]:
#Check for Null
df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [101]:
#Inspect Unique values using ".unique"
print(df['Dept'].unique())
print(df['Age'].unique())
print(df['Remote?'].unique())

<StringArray>
['IT', 'hr', 'Mktng', 'Customer Care', 'marketing', 'Finance', nan, 'HR']
Length: 8, dtype: str
<StringArray>
['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']
Length: 10, dtype: str
<StringArray>
['Yes', 'No', 'Y', 'N', 'yes', 'no', nan, 'True']
Length: 8, dtype: str

In [102]:
#Access values in a column
df['Salary($)']

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
5       4,300
6        5800
7        5000
8      4700.0
9        4400
Name: Salary($), dtype: str

In [103]:
#Revealing all characters in a column value using '.to_list'
df['fullName'].to_list()

['  Alice Johnson  ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM  davis',
 'Jane Miller',
 'Chris taylor']

In [104]:
#7th May, 2026
#Data Cleaning
#Renaming using ".rename" and ",inplace=True"
df.rename(columns={
    "EmpId": "emp_id",
    "fullName": "full_name",
    "Dept": "department",
    "Age": "age",
    "Salary($)": "salary",
    "JoinDate": "join_date",
    "Performance": "performance",
    "Remote?": "remote"
},inplace=True)

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [105]:
#Columns Transformation using 
df['full_name'] = (
    df['full_name']
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
)

df['full_name'].to_list()

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,Micheal Smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,Sarah Lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,John Brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,Tom Davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris Taylor,marketing,28,4400,2022-02-05,91,True

In [106]:
#Replacing inconsistent values
df.replace({
    'hr': 'HR',
    'Mktng': 'Marketing',
    'marketing': 'Marketing',
    None: np.nan
}, inplace=True)

df['department']

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7              NaN
8               HR
9        Marketing
Name: department, dtype: str

In [107]:
#Cleaning the Age Column
#def defines function
#isinstance(value) helps confirm the data type
#isdigit returns numbers that are in string format
#you must define the function "df['age'] = "

def clean_age(value):
    if value == "thirty-five":
        return 25
    elif isinstance(value, (int,float)):
        return (value)
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan
df['age'] = df['age'].apply(clean_age)
df['age']

0    29.0
1    25.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [108]:
#Clean Salary

df['salary'] = (
    df['salary']
    .astype(str)
    .replace(r"[$,]", "", regex=True)
    .replace("NaN", np.nan)
    .astype(float)
)

df['salary']

0    5500.50
1    4800.00
2    4200.75
3        NaN
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [109]:
#Clean Perfomance
df['performance'] = (
    df['performance']
    .astype(str)
    .replace(r"%", " ", regex=True)
    .replace("None", np.nan)
    .astype(float)
)
df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7     NaN
8    79.0
9    91.0
Name: performance, dtype: float64

In [110]:
#Cleaning remote

df.replace({
    "yes": "Yes",
    "no": "No",
    "N": "No",
    "Y": "Yes",
    "Y": "Yes",
    "True": "Yes",
    None: np.nan,
}, inplace=True)

df

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,12-04-2021,87.0,Yes
1,102,Micheal Smith,HR,25.0,4800.00,2020.11.01,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,"Jan 18, 2022",90.0,Yes
3,104,David Kim,IT,31.0,NaN,2019/9/25,65.0,No
4,105,NaN,Customer Care,42.0,6100.00,07/05/18,82.0,Yes
5,106,John Brown,Marketing,27.0,4300.00,2021-10-14,75.0,No
6,107,Emma Wilson,Finance,33.0,5800.00,2019/12/01,88.0,Yes
7,108,Tom Davis,NaN,30.0,5000.00,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.00,"May 10th, 2021",79.0,NaN
9,110,Chris Taylor,Marketing,28.0,4400.00,2022-02-05,91.0,Yes

In [111]:
#Cleaning inconsistent date value using pd.to_datetime(df['join_date'] 
#pd.to_datetime(df['join_date'] cannot handle complex date format, so we need to import "parser" from dateutil

#df['join_date'] = pd.to_datetime(df['join_date'], errors="coerce")
#df['join_date']

def date_parser(date_str):
    try:
        return parser.parse(date_str, dayfirst=True)
    except Exception:
        return pd.NaT

df['join_date'] = df['join_date'].apply(date_parser)
df['join_date']

0   2021-04-12
1   2020-01-11
2   2022-01-18
3   2019-09-25
4   2018-05-07
5   2021-10-14
6   2019-01-12
7   2020-03-22
8   2021-05-10
9   2022-05-02
Name: join_date, dtype: datetime64[us]

In [112]:
#Changing number in string format using ".to_numeric"
df['emp_id'] = pd.to_numeric(df['emp_id'], errors='coerce')
df['emp_id']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: emp_id, dtype: int64

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   emp_id       10 non-null     int64
 1   full_name    9 non-null      str
 2   department   9 non-null      str
 3   age          9 non-null      float64
 4   salary       9 non-null      float64
 5   join_date    10 non-null     datetime64[us]
 6   performance  9 non-null      float64
 7   remote       9 non-null      str
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 772.0 bytes

In [114]:
#Handling missing values using ".fillna"
df['full_name'] = df['full_name'].fillna('Unknown')
df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: str

In [117]:
#Replacing the missing value in department with mode

df['department'] = df['department'].fillna(df['department'].mode()[0])
df['department']

0               IT
1               HR
2        Marketing
3               IT
4    Customer Care
5        Marketing
6          Finance
7        Marketing
8               HR
9        Marketing
Name: department, dtype: str

In [119]:
#Replacing the missing value in age with the median
df['age'] = df['age'].fillna(df['age'].median())
df['age']

0    29.0
1    25.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8    29.0
9    28.0
Name: age, dtype: float64

In [123]:
#Replacing the missing value in salary with the median

df['salary'] = df['salary'].fillna(df['salary'].median())
df['salary']

0    5500.50
1    4800.00
2    4200.75
3    4800.00
4    6100.00
5    4300.00
6    5800.00
7    5000.00
8    4700.00
9    4400.00
Name: salary, dtype: float64

In [124]:
#Replacing the missing value in performance with the median
df['performance'] = df['performance'].fillna(df['performance'].median())
df['performance']

0    87.0
1    73.0
2    90.0
3    65.0
4    82.0
5    75.0
6    88.0
7    82.0
8    79.0
9    91.0
Name: performance, dtype: float64

In [127]:
df['remote'] = df['remote'].fillna(df['remote'].mode()[0])
df['remote']

0    Yes
1     No
2    Yes
3     No
4    Yes
5     No
6    Yes
7    Yes
8    Yes
9    Yes
Name: remote, dtype: str

In [131]:
#Checking for missing values

df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   emp_id       10 non-null     int64
 1   full_name    10 non-null     str
 2   department   10 non-null     str
 3   age          10 non-null     float64
 4   salary       10 non-null     float64
 5   join_date    10 non-null     datetime64[us]
 6   performance  10 non-null     float64
 7   remote       10 non-null     str
dtypes: datetime64[us](1), float64(3), int64(1), str(3)
memory usage: 772.0 bytes

emp_id         0
full_name      0
department     0
age            0
salary         0
join_date      0
performance    0
remote         0
dtype: int64

In [133]:
#Filtering using column names (field)

df['full_name']

0    Alice Johnson
1    Micheal Smith
2        Sarah Lee
3        David Kim
4          Unknown
5       John Brown
6      Emma Wilson
7        Tom Davis
8      Jane Miller
9     Chris Taylor
Name: full_name, dtype: str

In [135]:
#Filtering for the first 5 fields using .head
df.head()

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.50,2021-04-12,87.0,Yes
1,102,Micheal Smith,HR,25.0,4800.00,2020-01-11,73.0,No
2,103,Sarah Lee,Marketing,26.0,4200.75,2022-01-18,90.0,Yes
3,104,David Kim,IT,31.0,4800.00,2019-09-25,65.0,No
4,105,Unknown,Customer Care,42.0,6100.00,2018-05-07,82.0,Yes

In [137]:
#Filtering out some fields
df[['full_name', 'salary', 'performance']]

       full_name   salary  performance
0  Alice Johnson  5500.50         87.0
1  Micheal Smith  4800.00         73.0
2      Sarah Lee  4200.75         90.0
3      David Kim  4800.00         65.0
4        Unknown  6100.00         82.0
5     John Brown  4300.00         75.0
6    Emma Wilson  5800.00         88.0
7      Tom Davis  5000.00         82.0
8    Jane Miller  4700.00         79.0
9   Chris Taylor  4400.00         91.0

In [139]:
#Filtering by slicing using ".iloc"
df.iloc[0:3, 0:3]

   emp_id      full_name department
0     101  Alice Johnson         IT
1     102  Micheal Smith         HR
2     103      Sarah Lee  Marketing

In [140]:
#Filtering for conditions using ".loc"
df.loc[df['salary']>=5000]

,emp_id,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29.0,5500.5,2021-04-12,87.0,Yes
4,105,Unknown,Customer Care,42.0,6100.0,2018-05-07,82.0,Yes
6,107,Emma Wilson,Finance,33.0,5800.0,2019-01-12,88.0,Yes
7,108,Tom Davis,Marketing,30.0,5000.0,2020-03-22,82.0,Yes